### ISSUE TITLE
Admin - Woocommerce - Email Sender Options: From Email shouldn't be using the titan email address including the "Checkout - Paypal - Email Receiver" and also the "From Name" it should be using the correct name

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#1]
![2016-04-20_0843](https://cloud.githubusercontent.com/assets/13309730/14662628/a101c1aa-06d5-11e6-9b4d-d3659bcf035d.png)

**Comment by jsemblantetitanweb** [comment]
Can I ask what is the right name and email address that I will use on that specific fields so that I could input them. Thanks
