### ISSUE TITLE
General Pages - Single View: Inner ordered list is not move to the right a bit so that it will identify clearly that it is a inner list

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#14]
![2016-04-21_1010-subpara](https://cloud.githubusercontent.com/assets/13309730/14698202/fbe4e46a-07a9-11e6-9051-865c290e4122.png)

**Comment by roseliesromeo** [comment]
Please revert changes and follow the design.  Per design, bullet points are just inline with the content.
