### ISSUE TITLE
Homepage web copy not implemented properly

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#15]
H1- should be as per webcopy

![ss](https://cloud.githubusercontent.com/assets/13309730/14701976/b0777472-07c5-11e6-97d4-da600f9ca990.png)
![s11](https://cloud.githubusercontent.com/assets/13309730/14701992/c15e3776-07c5-11e6-909c-16c3031147d6.png)

**Comment by jsemblantetitanweb** [comment]
Base on the screenshot you've provided. The text being box on red is currently in a <h2> html tag. Should I make it <h1> ? And if yes, is it okay to have two <h1> elements ?
