### ISSUE TITLE
Home-Welcome section: 'View More' button should be 'View Detail' as stated in design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#18]
Applicable to all inner page buttons

![btn](https://cloud.githubusercontent.com/assets/13309730/14703449/804d526e-07cd-11e6-9eb0-451de4d12ee4.png)

**Comment by roseliesromeo** [comment]
View detail button in homepage is not editable.  The one in the titan theme options is for Locations page button setting
