### ISSUE TITLE
Admin-Forms: Contact email should be inputted.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#2]
![2016-04-20_0845-contemail](https://cloud.githubusercontent.com/assets/13309730/14662636/c242175c-06d5-11e6-97a1-c00bb087ed16.png)

**Comment by jsemblantetitanweb** [comment]
This shortcode of gravity form would dynamically get the email from the settings. But if user wants another specified email for this, User could just input directly the email the he/she wants for the notifications.
