### ISSUE TITLE
Home-Welcome section: Featured products are missing on home page

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#20]
![hmgap](https://cloud.githubusercontent.com/assets/13309730/14704261/7107905e-07d1-11e6-9a3f-c58cff75dc91.png)

**Comment by jsemblantetitanweb** [comment]
@note: User can set the featured products on the admin side by toggling the featured button on the Products section. I have also hide the section if there were no Featured product set in the admin side.
