### ISSUE TITLE
W3C Error's on Services page

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#4]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fgreenline-imp.stage.titanweb.com.au%2Fservices%2F
![2016-04-20_090serv](https://cloud.githubusercontent.com/assets/13309730/14662737/c65caa86-06d6-11e6-8359-2b6e1caee88b.png)

**Comment by jsemblantetitanweb** [comment]
This errors are all plugin issues.
