### ISSUE TITLE
W3C Error's on Precision Farming page

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#5]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fgreenline-imp.stage.titanweb.com.au%2F3852-2%2F

![2016-04-20_0905-precision_farming](https://cloud.githubusercontent.com/assets/13309730/14662788/3583d7c2-06d7-11e6-9c5a-3e952b295a06.png)

**Comment by jsemblantetitanweb** [comment]
Some of the errors are plugin issues or user errors
