### ISSUE TITLE
Prefooter brands:  Logos are smaller and blurry.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Greenline-AG#62]
![image](https://cloud.githubusercontent.com/assets/11186313/14812252/f3445952-0bce-11e6-80ff-48155f26a84c.png)

**Comment by jsemblantetitanweb** [comment]
Also it depends on the image being uploaded. If the image being uploaded is originally a blurry one. The issue will still occurs. Users need to upload high resolution images.
