### ISSUE TITLE
FOUC

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#7]
![fouc](https://cloud.githubusercontent.com/assets/13309730/14686975/c8332844-0758-11e6-83f1-66f423805216.png)

**Comment by roseliesromeo** [comment]
Not fixed in product single page.
![image](https://cloud.githubusercontent.com/assets/11186313/14805732/58633c78-0ba1-11e6-9a0b-da1aa5e15e94.png)
