### ISSUE TITLE
Contact Us page: Click-to call is not implemented properly.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Greenline-AG#9]
![isuu](https://cloud.githubusercontent.com/assets/13309730/14697919/697c8c8e-07a6-11e6-945d-78f5a4864bb9.png)

**Comment by roseliesromeo** [comment]
Click to call is not working in Lake Grace accordion panel. 
![image](https://cloud.githubusercontent.com/assets/11186313/14804898/b5295260-0b99-11e6-8308-a7bdc906afd6.png)
